@startuml
title Log In With Username And Password
actor User
skinparam linestyle ortho
rectangle ":Frontend" as frontend
rectangle ":Router" as router
rectangle ":UserService" as userService
rectangle ":UserController" as userController
rectangle ":UserRepository" as userRepository

database Database

User -right-> frontend: 1. handleLogInClick()
frontend -left-> User: 2. Show login form
User -right-> frontend: 3. .handleLogInSubmit(username, password)

frontend -right-> router: 4. POST/api/login
router -right-> userController: 5. .Login(username, password)
userController -right-> userService: 6. .Login(username, password)
userService -right-> userRepository: 7. .Login(username, password)
userRepository -down-> Database: 8. SELECT * FROM users WHERE username = @username AND password = @password

Database -up-> userRepository: 9. User, Error
userRepository -left-> userService: 10. User, Error

userService -left-> userController: 11. [Error != Null] User, Error
userController -left-> router: 12. 401 Unauthorized
router -left-> frontend: 13. 401 Unauthorized
frontend -left-> User: 14. Show error 'Invalid username or password'

userService -left->userController: 15. [User == Null] User, Error
userController -left-> router: 16. 404 Not Found
router -left-> frontend: 17. 404 Not Found
frontend -left-> User: 18. Show error 'User not found'

userService -right-> userRepository: 19. .GetSessionToken(username)
userRepository -left-> userService: 20. SessionToken
userService -up-> userService: 21. .SetSessionToken(SessionToken)

userService -left-> userController: 22. User with Session Token
userController -left-> router: 23. 200 OK
router -left-> frontend: 24. 200 OK
frontend -left-> User: 25. Show success 'Logged in'

@enduml