@startuml
actor User
skinparam linestyle ortho
rectangle ":Frontend" as frontend
rectangle ":Router" as router
rectangle ":UserService" as userService
rectangle ":UserController" as userController
rectangle ":UserRepository" as userRepository

database Database

User -right-> frontend: 1. .handleCreateAccountClick()
frontend -left-> User: 2. Show crate account form
User -right-> frontend: 3. .handleCreateAccountSubmit(username, password, email)

frontend -right-> router: 4. POST/api/users

router -right-> userController: 5. CreateUser(username, password, email)
userController -right-> userService: 6. CreateUser(username, password, email)
userService -right-> userRepository: 7. CreateUser(username, password, email)
userRepository -down-> Database: 8. INSERT INTO users(username, password, email) VALUES (@username, @password, @email)

Database -up-> userRepository: 9. User, Error
userRepository -left-> userService: 10. User, Error
userService -left->userController: 11. User, Error

userController -left-> router: 12. 201 Created
router -left-> frontend: 13. 201 Created

frontend -left-> User: 14. Show success Account created
@enduml