@startuml
title Create quiz

actor User
skinparam linestyle ortho
rectangle ":Middleware" as middleware
rectangle ":Frontend" as frontend
rectangle ":Router" as router

rectangle ":ClassController" as classController
rectangle ":ClassService" as classService
rectangle ":ClassRepository" as classRepository


rectangle ":CourseController" as courseController
rectangle ":CourseService" as courseService
rectangle ":CourseRepository" as courseRepository

rectangle ":QuizController" as quizController
rectangle ":QuizService" as quizService
rectangle ":QuizRepository" as quizRepository

database Database

frontend -right-> router: 1. GET/api/classes
router -right-> middleware: 2. Use(Middleware)
middleware -up-> middleware: 3. .Verify()

middleware -left-> router: 4.[Unauthorized (401 unauthorized)] 401 Unauthorized
router -left-> frontend: 5. 401 Unauthorized
frontend -left-> User: 6. Show error 'Please log in'

middleware -left-> router: 7.[Authorized] Route to Router
router -right-> classController: 8. .GetAllClases()
classController -right-> classService: 9. .GetAllClases()
classService -right-> classRepository: 10 .GetAllClases()

classRepository -right-> Database: 11. SELECT * FROM classes WHERE owner_id = @user_id
Database -left-> classRepository: 12. Classes, Error
classRepository -left-> classService: 13. classes, Error
classService -left-> classController: 14. classes, Error

classController -left-> router: 15. [Error != full] 500 Internet Server Error
router -left-> frontend: 16. 500 Internet Server Error
frontend -left-> User: 17. Show error 'Failed to fetch classes'

classController -left-> router: 16. [Error != full] 404 Not Found
router -left-> frontend: 16. 404 Not Found
frontend -left-> User: 17. Show message 'Class not found'


@enduml